module.exports = {
  SET_RSVP: 'SET_RSVP',
  UPDATE_PERSON_RSVP: 'UPDATE_PERSON_RSVP',
  UPDATE_PLUS: 'UPDATE_PLUS',
  UPDATE_RSVP_QUERY: 'UPDATE_RSVP_QUERY',
  UPDATE_RSVP_RESULT: 'UPDATE_RSVP_RESULT'
};
