module.exports = {
  SET_RSVP: 'SET_RSVP',
  UPDATE_PERSON_RSVP: 'UPDATE_PERSON_RSVP',
  UPDATE_PLUS: 'UPDATE_PLUS',
  UPDATE_RSVP_QUERY: 'UPDATE_RSVP_QUERY',
  UPDATE_RSVP_RESULT: 'UPDATE_RSVP_RESULT',
  UPDATE_GUEST_NAME: 'UPDATE_GUEST_NAME',
  UPDATE_GUEST_EMAIL: 'UPDATE_GUEST_EMAIL',
  ADD_GUEST: 'ADD_GUEST',
  UPDATE_SHORT_NAME: 'UPDATE_SHORT_NAME',
  UPDATE_PLUS_ALLOWED: 'UPDATE_PLUS_ALLOWED',
  UPDATE_VENUE_MARKERS: 'UPDATE_VENUE_MARKERS',
  UPDATE_GUIDE_MARKERS: 'UPDATE_GUIDE_MARKERS',
  SHOW_GUIDE_MAP_INFO: 'SHOW_GUIDE_MAP_INFO'
};
